server:
  port: 8081

logging:
  file: UBoot-Api-Service
  path: ./log/
  level:
    com:
      uyibai:
        uboot : debug
        
spring:
  profiles:
    active: @profileActive@
  servlet:
    multipart:
      max-request-size: 1024MB # 最大请求大小
      max-file-size: 1024MB # 最大文件上传大小
  aop:
    auto: true
  application:
    name: Uboot-Api-Service
  config:
    name: Uboot-Api-Service
  main:
    banner-mode: log
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 10000
app:
  name: @app.name@
  version: @app.version@
  updateAt: @maven.build.timestamp@

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-handlers-package: com.uyibai.uboot.common.config.mybatis

