# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/uboot?serverTimezone=Hongkong&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
